const driverNoID = {
  firstName: 'Archy',
  lastName: 'Ballsford',
  address: '101 SW First St.',
  city: 'Williamsburg',
  state: 'VA',
  zip: 22096,
  password: 'cdsa;fkdsja',
  email: 'darkside69@caremail.com',
  phoneNumber: '7039945979',
  phoneType: 'cell',
  contracts: [],
  paymentInfo: [],
};
const updatedDriverNoId = {
  firstName: 'Archy',
  lastName: 'Ballsford',
  address: '101 SW First St.',
  password: 'cdsa;fkdsja',
  city: 'Williamsburg',
  state: 'VA',
  zip: 22096,
  email: 'gmail@caremail.com',
  phoneNumber: '7039945979',
  phoneType: 'cell',
  contracts: [],
  paymentInfo: [],
} 
const driverID = {
  _id: '5da39be0d4381609f9bc9c26',
  firstName: 'Jacky',
  lastName: 'Ballsford',
  address: '101 SW First St.',
  city: 'Williamsburg',
  state: 'VA',
  zip: 22096,
  email: 'darkside69@caremail.com',
  phoneNumber: '7039945979',
  phoneType: 'cell',
  password: 'cdsa;fkdsja',
  contracts: [],
  paymentInfo: [],
};
module.exports = [driverNoID, driverID, updatedDriverNoId];
